export const COMMERCIAL_FLIGHT_ROW_COUNT = 20
export const PRIVATE_FLIGHT_ROW_COUNT = 5

export const USD = 'USD'
export const BASE_COMMERCIAL_FLIGHT_PRICE_UNITS = 100
export const BASE_COMMERCIAL_FLIGHT_PRICE_SUB_UNITS = 0
export const BASE_PRIVATE_FLIGHT_UNITS = 500
export const BASE_PRIVATE_FLIGHT_SUB_UNITS = 500
export const SEAT_VOLITILITY = 100